version: '3'
services:
  studyup:
    image: studyup-img
    ports:
     - "8080:8080"
  
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  
  ng:
    image: nginx-img
    ports:
     - "8888:8888"
    links:
     - "redis"